export const products = [
  {
    id: "1",
    name: "iPhone 16",
    description: "12 MP kamera, A16 çip, 128 GB depolama",
    price: 799,
    brand: "Apple",
    category: "Phone",
    inStock: true,
    image:
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-pro-model-unselect-gallery-1-202309?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1693009283423",
    reviews: [],
  },
  {
    id: "2",
    name: "Samsung Galaxy S23",
    description: "108 MP ana kamera, 8K video kayıt, 256 GB depolama",
    price: 899,
    brand: "Samsung",
    category: "Phone",
    inStock: true,
    image:
      "https://images.samsung.com/is/image/samsung/p6pim/tr/2302/gallery/tr-galaxy-s23-sm-s911bzkgmea-534866717?$216_216_PNG$",
    reviews: [],
  },
  {
    id: "3",
    name: "MacBook Pro 14",
    description: "M2 Pro çip, 16 GB RAM, 512 GB SSD",
    price: 1999,
    brand: "Apple",
    category: "Laptop",
    inStock: true,
    image:
      "https://www.apple.com/v/macbook-pro-14-and-16/b/images/overview/hero/hero_intro_endframe__e6khcva4hkeq_large.jpg",
    reviews: [],
  },
  {
    id: "4",
    name: "Huawei MatePad Pro",
    description: "12.6 inç OLED ekran, Kirin 9000 çip, 128 GB depolama",
    price: 699,
    brand: "Huawei",
    category: "Tablet",
    inStock: true,
    image:
      "https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/pdp/tablets/matepad-pro-13-2/images/kv/pc/kv.jpg",
    reviews: [],
  },
  {
    id: "5",
    name: "Sony WH-1000XM5",
    description: "Gürültü önleyici kulaklık, 30 saat pil ömrü",
    price: 349,
    brand: "Sony",
    category: "Headphones",
    inStock: true,
    image:
      "https://www.sony.com.tr/image/1d7d5e2c6c6f9b8a5a0d0e0f0e0f0e0f?fmt=pjpeg&wid=1200&hei=1200",
    reviews: [],
  },
  {
    id: "6",
    name: "Apple Watch Series 8",
    description: "45 mm, GPS + Cellular, kan oksijen ölçümü",
    price: 429,
    brand: "Apple",
    category: "Smartwatch",
    inStock: false,
    image:
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MQDY3ref_VW_34FR+watch-49-titanium-ultra_VW_34FR_WF_CO?wid=750&hei=712&trim=1%2C0&fmt=p-jpg&qlt=95&.v=1660713657930%2C1660927566964",
    reviews: [],
  },
  {
    id: "7",
    name: "Xiaomi Redmi Note 12",
    description: "AMOLED ekran, 50 MP kamera, 5000 mAh pil",
    price: 299,
    brand: "Xiaomi",
    category: "Phone",
    inStock: true,
    image:
      "https://i01.appmifile.com/webfile/globalimg/products/pc/redmi-note-12/specs-header.png",
    reviews: [],
  },
  {
    id: "8",
    name: "Dell XPS 15",
    description: "15.6 inç 4K ekran, Intel i7, 16 GB RAM, 1 TB SSD",
    price: 1799,
    brand: "Dell",
    category: "Laptop",
    inStock: true,
    image:
      "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-15-9520/media-gallery/notebook-xps-9520-t-gallery-1.psd?fmt=png-alpha&pscan=auto&scl=1&wid=4000&hei=4000&qlt=100,0&resMode=sharp2&size=4000,4000",
    reviews: [],
  },
  {
    id: "9",
    name: "Samsung Galaxy Tab S8",
    description: "11 inç LTPS ekran, S Pen dahil, 128 GB depolama",
    price: 649,
    brand: "Samsung",
    category: "Tablet",
    inStock: true,
    image:
      "https://images.samsung.com/is/image/samsung/p6pim/tr/2202/gallery/tr-galaxy-tab-s8-ultra-wifi-sm-x900nzaamea-thumb-530606128?$216_216_PNG$",
    reviews: [],
  },
  {
    id: "10",
    name: "AirPods Pro 2",
    description: "Aktif gürültü engelleme, uzamsal ses, MagSafe şarj",
    price: 249,
    brand: "Apple",
    category: "Headphones",
    inStock: true,
    image:
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MQD83?wid=572&hei=572&fmt=jpeg&qlt=95&.v=1660803972361",
    reviews: [],
  },
];
